"""empty message

Revision ID: 228c30e079e
Revises: 580170c6dea
Create Date: 2014-05-30 10:01:46.325688

"""

# revision identifiers, used by Alembic.
revision = '228c30e079e'
down_revision = '580170c6dea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_monkeys_email'), 'monkeys', ['email'], unique=True)
    op.create_index(op.f('ix_monkeys_name'), 'monkeys', ['name'], unique=False)
    op.drop_index('ix_monkeys_best_friend', table_name='monkeys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_monkeys_best_friend', 'monkeys', ['best_friend'], unique=False)
    op.drop_index(op.f('ix_monkeys_name'), table_name='monkeys')
    op.drop_index(op.f('ix_monkeys_email'), table_name='monkeys')
    ### end Alembic commands ###
