"""empty message

Revision ID: 25d3410b9f6
Revises: None
Create Date: 2014-05-27 21:54:20.587367

"""

# revision identifiers, used by Alembic.
revision = '25d3410b9f6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('monkeys', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('monkeys', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('monkeys', 'password_hash')
    op.drop_column('monkeys', 'birth_date')
    ### end Alembic commands ###
