"""empty message

Revision ID: 3bc388d55b3
Revises: None
Create Date: 2014-05-31 12:44:19.391912

"""

# revision identifiers, used by Alembic.
revision = '3bc388d55b3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('best_friend_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monkeys_email'), 'monkeys', ['email'], unique=True)
    op.create_index(op.f('ix_monkeys_name'), 'monkeys', ['name'], unique=False)
    op.create_table('friendships',
    sa.Column('monkey_1', sa.Integer(), nullable=False),
    sa.Column('monkey_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monkey_1'], ['monkeys.id'], ),
    sa.ForeignKeyConstraint(['monkey_2'], ['monkeys.id'], ),
    sa.PrimaryKeyConstraint('monkey_1', 'monkey_2')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_index(op.f('ix_monkeys_name'), table_name='monkeys')
    op.drop_index(op.f('ix_monkeys_email'), table_name='monkeys')
    op.drop_table('monkeys')
    ### end Alembic commands ###
