"""empty message

Revision ID: 45ec927d56c
Revises: 228c30e079e
Create Date: 2014-05-30 11:06:51.704063

"""

# revision identifiers, used by Alembic.
revision = '45ec927d56c'
down_revision = '228c30e079e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('best_friend_id', sa.Integer(), nullable=True))
    op.drop_column('monkeys', 'best_friend')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('best_friend', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('monkeys', 'best_friend_id')
    ### end Alembic commands ###
