"""empty message

Revision ID: 580170c6dea
Revises: None
Create Date: 2014-05-29 16:30:14.902144

"""

# revision identifiers, used by Alembic.
revision = '580170c6dea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friendships',
    sa.Column('monkey_1', sa.Integer(), nullable=False),
    sa.Column('monkey_2', sa.Integer(), nullable=False),
    sa.Column('best_friend', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monkey_1'], ['monkeys.id'], ),
    sa.ForeignKeyConstraint(['monkey_2'], ['monkeys.id'], ),
    sa.PrimaryKeyConstraint('monkey_1', 'monkey_2')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_table('monkeys')
    ### end Alembic commands ###
